<MenuScreen>:
    Label:
        id: user_id_label
        size_hint: (0.2, 0.1)
        pos_hint: {"top": 1}
        text: "huyara"

    BoxLayout:
        size_hint: (0.6, 0.4)
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        orientation: "vertical"
        BoxLayout:
            Label:
                size_hint_x: 0.5
                text: "Invite user"
            TextInput:
                multiline: False
                text: ""
                on_text_validate: root.send_invite(self.text)
        BoxLayout:
            Label:
                id: invite_from_label
                size_hint_x: 0.5
                text: "Invite from"
            Button:
                text: "Accept"
                on_press: root.accept_invite()


<GameScreen>:
    canvas:
        Color:
            rgba: 1, 1, 1, 0.5
        Rectangle:
            size: 300, 150
            pos: 150, 150
